# exclude SafeMath when calculating test coverage
# https://eth-brownie.readthedocs.io/en/v1.10.3/config.html#exclude_paths

# networks:
    
#- name: Ethereum
networks:
  default: development
  development:
      gas_limit: max
      gas_buffer: 1
      gas_price: 0
      max_fee: null
      priority_fee: null
      reverting_tx_gas_limit: max
      default_contract_owner: true
  # - cmd: ganache-cli
  #   cmd_settings:
  #       port: 8545
  #       gas_limit: 6721975
  #       accounts: 10
  #       chain_id: 1337
  #       network_id: 1588949648
  #       evm_version: istanbul
  #       fork: null
  #       mnemonic: purse melody atom walk pelican buyer hire swamp expire left lady three
  #       block_time: 0
  #       default_balance: 100
  #       time: 2020-05-08T14:54:08+0000
  #       unlock: null

  kovan:
    verify: False
    update_interval: 60
    gas_limit: 12500000
    gas_buffer: 1.1
    gas_price: 30000000
    max_fee: null
    priority_fee: null
    reverting_tx_gas_limit: false
    default_contract_owner: false
    explorer: 

  polygon-mumbai:
    chainId: 80001
    gas_price: 30000000

# dotenv: .env



compiler:
    solc: 
      version: 0.5.17
      remappings:
        # - "@openzeppelin=./node_modules/@openzeppelin"
      #   - "@chainlink=/home/loophe/brownie/dnd/node_modules/@chainlink"

wallets:
  from_key: ${PRIVATE_KEY}
  from_key1: ${PRIVATE_KEY1}

console:
  show_colors: true
  color_style: monokai
  auto_suggest: true
  completions: true
  editing_mode: emacs

keys:
  ALCHEMYAPI_TOKEN: ${ALCHEMYAPI_TOKEN}
  ALCHEMYAPI_POLYGON_TOKEN: ${ALCHEMYAPI_POLYGON_TOKEN}
  WEB3_INFURA_PROJECT_ID: ${WEB3_INFURA_PROJECT_ID}
  ETHERSCAN_TOKEN: ${ETHERSCAN_TOKEN}
  BSCSCAN_TOKEN: ${BSCSCAN_TOKEN}
  ETHPLORER_API_KEY: ${ETHPLORER_API_KEY}
  POLYGONSCAN_TOKEN: ${POLYGONSCAN_TOKEN}

